export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_CATEGORY_AMOUNT = "UPDATE_CATEGORY_AMOUNT";

export const SELECT_MONTH = "SELECT_MONTH";

export const UPDATE_DATA = "UPDATE_DATA";

export const SELECT_SCREEN = "SELECT_SCREEN";

export const SELECT_YEAR = "SELECT_YEAR";